version: 2
project_name: granary

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    binary: granary
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}-Darwin-{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^Merge pull request'
      - '^Merge branch'
      - '^docs:'
      - '^chore:'
      - '^test:'

release:
  github:
    owner: skorten
    name: granary
